import React from 'react';
import { motion } from 'motion/react';
import { 
  Book, 
  Code, 
  Terminal, 
  Shield, 
  Users, 
  Zap, 
  Cpu, 
  FileText, 
  Settings,
  ChevronRight,
  Info
} from 'lucide-react';

export default function Documentation() {
  const sections = [
    { id: 'overview', title: 'System Overview', icon: Book },
    { id: 'features', title: 'Core Features', icon: Zap },
    { id: 'roles', title: 'Roles & Permissions', icon: Users },
    { id: 'workflow', title: 'Operational Workflow', icon: Settings },
    { id: 'ai', title: 'AI Copilot', icon: Cpu },
    { id: 'compliance', title: 'Compliance System', icon: Shield },
    { id: 'security', title: 'Security & Access', icon: Lock }
  ];

  return (
    <div className="flex gap-12 max-w-7xl mx-auto py-12 animate-in fade-in duration-700">
      {/* Sidebar Nav */}
      <aside className="w-64 flex-shrink-0 sticky top-12 h-fit hidden lg:block">
        <div className="tech-label mb-6 text-aviator-amber">Documentation</div>
        <nav className="space-y-2">
          {sections.map(s => (
            <a 
              key={s.id} 
              href={`#${s.id}`}
              className="flex items-center gap-3 p-3 rounded-sm hover:bg-white/5 transition-all group text-aviator-text-dim hover:text-aviator-text"
            >
              <s.icon className="w-4 h-4" />
              <span className="text-sm font-medium">{s.title}</span>
            </a>
          ))}
        </nav>
      </aside>

      {/* Content */}
      <main className="flex-1 space-y-24 pb-24">
        <section id="overview" className="space-y-6">
          <h1 className="text-4xl font-bold tracking-tighter uppercase italic border-b border-aviator-border pb-4">Overview</h1>
          <p className="text-lg text-aviator-text leading-relaxed">
            AeroCompliance is an integrated aviation maintenance execution system designed to automate technical record-keeping and ensure continuous airworthiness compliance. By leveraging Large Language Models (LLMs), the system translates informal maintenance notes into structured, regulatory-compliant technical logs.
          </p>
          <div className="p-6 bg-aviator-amber/5 border border-aviator-amber/20 rounded-sm">
             <div className="flex gap-3 text-aviator-amber font-bold tech-label mb-2">
               <Info className="w-4 h-4" /> COMPLIANCE NOTICE
             </div>
             <p className="text-sm text-aviator-text leading-relaxed">
               All logs generated by the AI system must be reviewed by an authorized Engineer before being committed to the permanent aircraft registry.
             </p>
          </div>
        </section>

        <section id="features" className="space-y-8">
          <h2 className="text-2xl font-bold tracking-tight uppercase border-l-4 border-aviator-amber pl-4">Core Features</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="tech-card p-6 space-y-3">
              <h3 className="font-bold">AI Log Generation</h3>
              <p className="text-xs text-aviator-text-dim">Processes natural language input into standardized formats including ATA chapters and specific issue/action narratives.</p>
            </div>
            <div className="tech-card p-6 space-y-3">
              <h3 className="font-bold">Compliance Validation</h3>
              <p className="text-xs text-aviator-text-dim">Automated rule-based engine that detects incomplete mandatory fields or regulatory inconsistencies.</p>
            </div>
            <div className="tech-card p-6 space-y-3">
              <h3 className="font-bold">Aircraft Management</h3>
              <p className="text-xs text-aviator-text-dim">Full lifecycle tracking of airframe assets with tiered approval workflows for new registry entries.</p>
            </div>
            <div className="tech-card p-6 space-y-3">
              <h3 className="font-bold">Unified Notification</h3>
              <p className="text-xs text-aviator-text-dim">Real-time alerts for critical maintenance events, approval requests, and compliance alerts.</p>
            </div>
          </div>
        </section>

        <section id="roles" className="space-y-8">
          <h2 className="text-2xl font-bold tracking-tight uppercase border-l-4 border-aviator-amber pl-4">User Roles & Permissions</h2>
          <table className="w-full tech-card border-none overflow-hidden">
            <thead>
              <tr className="bg-black/10 dark:bg-white/5">
                <th className="p-4 tech-label text-left">Role</th>
                <th className="p-4 tech-label text-left">Primary Authority</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-aviator-border">
              <tr>
                <td className="p-4 font-bold text-aviator-amber">Technician</td>
                <td className="p-4 text-sm">Initiate maintenance events, record AI-assisted logs, manage self-profile.</td>
              </tr>
              <tr>
                <td className="p-4 font-bold text-aviator-amber">Engineer</td>
                <td className="p-4 text-sm">Review, approve, or reject technical logs. Authority to sign off on specific actions.</td>
              </tr>
              <tr>
                <td className="p-4 font-bold text-aviator-amber">QA Officer</td>
                <td className="p-4 text-sm">Validate system-wide compliance records and audit log integrity.</td>
              </tr>
              <tr>
                <td className="p-4 font-bold text-aviator-amber">Planner</td>
                <td className="p-4 text-sm">Analyze fleet trends and register new aircraft assets (requires Admin approval).</td>
              </tr>
              <tr>
                <td className="p-4 font-bold text-aviator-amber">Supervisor</td>
                <td className="p-4 text-sm">Operational oversight and fleet-wide status monitoring. Limited asset updates.</td>
              </tr>
              <tr>
                <td className="p-4 font-bold text-aviator-amber">Admin</td>
                <td className="p-4 text-sm">Full system authority, user management, and registry final approval.</td>
              </tr>
            </tbody>
          </table>
        </section>

        <section id="workflow" className="space-y-8">
          <h2 className="text-2xl font-bold tracking-tight uppercase border-l-4 border-aviator-amber pl-4">Operational Workflow</h2>
          <div className="flex flex-col gap-4 relative">
             <div className="absolute left-[19px] top-4 bottom-4 w-px bg-aviator-border" />
             {[
               { role: 'Technician', action: 'Input raw notes → AI creates Draft Log' },
               { role: 'Engineer', action: 'Review Draft → Approve/Reject' },
               { role: 'QA Officer', action: 'System-wide compliance audit' },
               { role: 'Planner', action: 'Fleet data analysis & trend reporting' },
               { role: 'Admin', action: 'System monitoring & final registry control' }
             ].map((step, i) => (
                <div key={i} className="flex gap-6 items-center relative z-10">
                   <div className="w-10 h-10 rounded-full bg-aviator-card border border-aviator-border flex items-center justify-center font-bold text-aviator-amber">
                     {i+1}
                   </div>
                   <div className="tech-card flex-1 p-4 flex justify-between items-center">
                      <span className="font-bold text-xs uppercase tracking-widest">{step.role}</span>
                      <span className="text-sm text-aviator-text-dim italic">{step.action}</span>
                   </div>
                </div>
             ))}
          </div>
        </section>

        <section id="ai" className="space-y-8">
          <h2 className="text-2xl font-bold tracking-tight uppercase border-l-4 border-aviator-amber pl-4">AI Copilot</h2>
          <p className="text-aviator-text leading-relaxed">
            The AI engine uses the <strong>Gemini 1.5 Pro</strong> model to parse technical maintenance nomenclature. It recognizes patterns such as ATA-100/iSpec 2200 standards and automatically identifies technical discrepancy categories.
          </p>
          <div className="tech-card p-6 bg-black/40 font-mono text-[11px] space-y-2">
            <div className="text-aviator-amber">// AI Engine Input Example</div>
            <div className="text-white">"Found slight hydraulic leakage on main landing gear strut, replaced seals."</div>
            <div className="text-aviator-amber mt-4">// Semantic Reconstruction Output</div>
            <div className="text-white">
              {`{
  "ata_chapter": "32-11",
  "component": "Main Landing Gear Strut",
  "issue": "Hydraulic fluid leakage detected at seal interface",
  "action": "Dismantled strut, inspected piston surface, replaced primary and secondary seals"
}`}
            </div>
          </div>
        </section>

        <section id="security" className="space-y-8">
          <h2 className="text-2xl font-bold tracking-tight uppercase border-l-4 border-aviator-amber pl-4">Security & Access</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
             <div className="space-y-4">
                <h3 className="font-bold text-lg flex items-center gap-2 italic">
                  <Shield className="w-5 h-5 text-aviator-amber" /> Hierarchical Control
                </h3>
                <p className="text-xs text-aviator-text-dim leading-relaxed">
                  Access is governed by specific role definitions. Admin accounts require a secure primary secret key setup during initialization to prevent unauthorized command override.
                </p>
             </div>
             <div className="space-y-4">
                <h3 className="font-bold text-lg flex items-center gap-2 italic">
                  <Settings className="w-5 h-5 text-aviator-amber" /> Personnel Management
                </h3>
                <p className="text-xs text-aviator-text-dim leading-relaxed">
                  Administrators can instantly deactivate or suspend accounts. The system enforces strict license expiry tracking for all technical personnel.
                </p>
             </div>
          </div>
        </section>

        <section id="api" className="space-y-6 pt-12 border-t border-aviator-border">
          <div className="tech-label text-aviator-amber">API Endpoints Overview</div>
          <div className="space-y-4">
             {[
               { method: 'GET', endpoint: '/api/logs', desc: 'Fetch authorized technical records' },
               { method: 'POST', endpoint: '/api/aircraft', desc: 'Initiate new asset registration' },
               { method: 'POST', endpoint: '/api/aircraft/:id/approve', desc: 'Finalize registry entries (Admin Only)' },
               { method: 'GET', endpoint: '/api/users/profile', desc: 'Secure personnel record retrieval' }
             ].map((api, i) => (
               <div key={i} className="flex gap-4 items-center bg-black/5 p-3 rounded-sm">
                  <span className={`font-mono text-[10px] font-bold px-2 py-0.5 rounded-sm ${api.method === 'GET' ? 'bg-blue-500/20 text-blue-400' : 'bg-green-500/20 text-green-400'}`}>
                    {api.method}
                  </span>
                  <span className="font-mono text-xs text-aviator-text">{api.endpoint}</span>
                  <span className="text-[10px] text-aviator-text-dim ml-auto uppercase tracking-wider">{api.desc}</span>
               </div>
             ))}
          </div>
        </section>
      </main>
    </div>
  );
}

const Lock = (props: any) => (
  <svg 
    xmlns="http://www.w3.org/2000/svg" 
    width="24" 
    height="24" 
    viewBox="0 0 24 24" 
    fill="none" 
    stroke="currentColor" 
    strokeWidth="2" 
    strokeLinecap="round" 
    strokeLinejoin="round" 
    {...props}
  >
    <rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>
  </svg>
);
